doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Entity'
                prefix: 'App\User\Infrastructure\Doctrine\Entity'
                alias: User
            Photo:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Photo/Infrastructure/Doctrine/Entity'
                prefix: 'App\Photo\Infrastructure\Doctrine\Entity'
                alias: Photo

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
